In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime

In [2]:
pd.set_option('display.float_format', lambda x: f'{x:.2f}')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [3]:
tlc_taxi_zone_lookup = pd.read_csv("../data/mappings/taxi_zone_lookup.csv")
print(tlc_taxi_zone_lookup.shape[0], "rows,", tlc_taxi_zone_lookup.shape[1], "columns")
tlc_taxi_zone_lookup.head()

265 rows, 4 columns

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [4]:
FILE_PATH = r"../data/raw/yellow_tripdata_2026-05.parquet"
df = pd.read_parquet(FILE_PATH)
print(f"{df.shape[0]} rows, {df.shape[1]} columns")

4090836 rows, 20 columns

In [5]:
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag                  str
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [6]:
df = df[["tpep_pickup_datetime", "tpep_dropoff_datetime", "passenger_count", "trip_distance", "PULocationID", "DOLocationID", "payment_type", "fare_amount", "extra", "mta_tax","tip_amount", "tolls_amount", "improvement_surcharge", "total_amount", "congestion_surcharge", "Airport_fee", "cbd_congestion_fee"]]

df = df.rename(columns={
    "tpep_pickup_datetime": "pickup_datetime",
    "tpep_dropoff_datetime": "dropoff_datetime",
    "PULocationID": "pickup_location_id",
    "DOLocationID": "dropoff_location_id"
})

df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])
df['dropoff_datetime'] = pd.to_datetime(df['dropoff_datetime'])

payment_type_mapping = {
    0: "Flex Fare trip",
    1: "Credit card",
    2: "Cash",
    3: "No charge",
    4: "Dispute",
    5: "Unknown",
    6: "Voided trip"
}
df['payment_type'] = df['payment_type'].map(payment_type_mapping)

In [7]:
df.isna().sum()

pickup_datetime               0
dropoff_datetime              0
passenger_count          955371
trip_distance                 0
pickup_location_id            0
dropoff_location_id           0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     955371
Airport_fee              955371
cbd_congestion_fee            0
dtype: int64

In [8]:
# --- Pickup and Dropoff Datetime Columns ---
print(df['pickup_datetime'].min(), df['pickup_datetime'].max())
print(df['dropoff_datetime'].min(), df['dropoff_datetime'].max())

2008-12-31 23:05:53 2026-06-01 00:20:35
2009-01-01 17:08:07 2026-06-02 12:53:42

In [9]:
# --- Passenger Count Column ---
print(df['passenger_count'].value_counts())
print(df['passenger_count'].value_counts().sum())

passenger_count
1.00    2578718
2.00     395103
3.00      83959
4.00      52929
0.00      12533
5.00       7666
6.00       4553
8.00          3
9.00          1
Name: count, dtype: int64
3135465

In [10]:
# --- Trip Distance Column ---
print(df['trip_distance'].value_counts())
print(df['trip_distance'].value_counts().sum())

trip_distance
0.00         113031
0.90          40207
1.00          39612
0.80          39304
1.10          38820
1.20          37207
0.70          37061
1.30          35785
1.40          33603
1.50          32373
0.60          32335
1.60          30890
1.70          28948
1.80          26916
0.50          25852
1.90          25113
2.00          23306
2.10          22124
2.20          20347
2.30          18754
0.40          18381
2.40          17598
2.50          16145
2.60          15191
0.01          15071
2.70          14185
2.80          13295
2.90          12313
0.93          12092
0.92          12072
0.86          12021
0.96          12015
0.87          11969
1.01          11969
0.91          11937
0.97          11918
0.98          11918
1.04          11917
0.84          11899
1.02          11886
0.85          11851
0.94          11851
0.88          11843
1.06          11838
0.95          11837
1.03          11829
0.99          11822
0.89          11787
0.81          11781
1.07          11762
0.82          11740
1.05          11708
1.08          11693
1.13          11676
0.83          11673
1.14          11640
1.11          11635
3.00          11606
1.09          11605
0.77          11547
1.17          11531
1.16          11521
1.18          11502
1.12          11468
0.76          11453
0.79          11400
1.21          11342
0.78          11337
0.75          11312
1.19          11311
1.22          11280
1.24          11264
1.23          11212
1.15          11196
1.25          11147
1.28          11102
0.73          11098
1.26          11084
1.27          11081
0.74          11071
3.10          10995
0.72          10966
1.32          10896
1.29          10864
0.71          10845
1.34          10786
1.33          10763
1.35          10750
0.30          10707
1.31          10678
1.36          10641
1.38          10573
0.69          10566
1.39          10474
1.37          10469
1.41          10452
0.68          10451
0.67          10362
1.43          10307
0.66          10291
3.20          10223
1.44          10214
1.45          10109
1.42          10095
1.46          10081
1.47          10007
0.65           9996
0.64           9972
1.49           9957
1.51           9891
1.48           9833
1.53           9792
0.62           9749
3.30           9737
0.63           9711
1.54           9669
1.56           9577
1.55           9563
1.57           9536
1.52           9472
0.61           9461
1.58           9406
1.59           9383
1.61           9215
1.64           9198
3.40           9171
1.62           9128
1.63           9094
1.65           9045
0.59           9043
0.58           8975
1.67           8944
1.66           8919
1.69           8869
3.50           8768
0.57           8767
0.56           8723
1.68           8699
1.72           8689
1.73           8638
1.71           8567
1.75           8529
1.74           8372
1.76           8370
0.55           8318
1.78           8316
3.60           8248
1.77           8230
1.79           8183
1.81           8092
1.82           8066
1.83           8059
1.84           8058
0.54           8043
0.53           7909
1.88           7888
1.86           7863
1.85           7840
1.89           7775
1.87           7714
0.52           7695
1.92           7661
1.91           7645
1.93           7568
3.70           7567
1.95           7505
1.94           7437
3.80           7359
1.96           7359
0.51           7304
1.98           7285
1.99           7278
1.97           7241
3.90           7098
2.01           7080
2.02           7065
0.49           7019
2.03           7010
2.04           6916
2.05           6865
0.48           6801
2.06           6729
2.07           6697
0.47           6645
2.08           6641
4.00           6621
2.11           6604
2.13           6563
2.09           6543
2.14           6466
2.12           6464
2.15           6461
4.10           6450
2.16           6415
2.17           6383
0.46           6311
2.21           6275
2.18           6260
4.20           6198
2.19           6146
2.22           6063
0.45           6045
2.24           6008
2.25           5960
0.44           5897
2.23           5892
2.27           5891
2.28           5857
4.30           5826
2.26           5811
2.29           5810
2.33           5698
2.32           5687
4.40           5657
0.43           5656
2.31           5630
2.36           5547
2.35           5509
2.34           5501
2.37           5479
2.41           5468
2.38           5459
4.50           5422
0.42           5379
2.39           5332
2.43           5276
2.42           5248
2.44           5226
4.60           5213
0.41           5175
4.70           5103
2.45           5066
2.46           5055
2.48           5016
2.47           5014
2.49           4930
4.80           4927
2.51           4865
2.52           4858
2.54           4857
4.90           4846
2.53           4835
0.20           4746
2.57           4706
2.55           4705
2.58           4664
0.39           4634
2.56           4626
5.10           4573
0.02           4562
2.61           4539
5.00           4527
2.62           4511
2.59           4483
2.67           4472
2.64           4464
0.38           4424
2.65           4412
2.66           4390
2.63           4385
2.73           4364
2.68           4294
2.69           4275
5.20           4251
2.71           4230
2.78           4185
2.74           4171
0.37           4150
2.75           4097
5.30           4080
2.77           4078
2.76           4068
2.72           4017
5.40           3999
2.79           3979
2.82           3938
2.81           3926
2.84           3878
5.50           3877
2.86           3864
2.83           3862
2.85           3854
0.36           3839
2.88           3813
2.87           3801
0.35           3791
5.60           3763
2.89           3744
5.70           3711
2.92           3703
2.95           3682
2.91           3651
2.94           3600
2.97           3599
2.93           3585
2.96           3556
5.90           3517
2.98           3507
2.99           3495
0.34           3486
3.02           3485
3.04           3470
3.01           3464
5.80           3453
6.00           3426
3.05           3420
3.06           3403
3.03           3370
3.09           3356
3.08           3316
3.07           3286
0.33           3249
3.12           3232
6.20           3187
3.17           3176
3.13           3165
3.14           3163
3.18           3148
3.11           3142
6.10           3136
3.21           3126
3.19           3108
3.16           3103
3.15           3090
3.22           3088
6.40           3065
3.23           3045
6.50           3045
6.30           3020
3.27           3020
3.28           3019
3.26           3014
0.32           3002
3.24           2992
3.25           2976
3.33           2950
3.29           2940
6.60           2930
3.32           2913
6.80           2888
6.70           2879
3.34           2836
6.90           2826
3.31           2813
3.41           2812
3.44           2800
3.39           2769
3.36           2767
3.37           2762
3.38           2743
3.35           2735
0.31           2725
3.42           2721
3.45           2706
7.20           2683
7.10           2682
3.52           2676
3.47           2674
3.43           2670
7.00           2660
3.51           2625
7.30           2617
3.48           2613
3.49           2591
3.53           2582
3.46           2582
7.50           2578
3.56           2568
8.30           2518
3.57           2514
7.70           2507
3.55           2505
8.20           2504
3.54           2496
7.90           2490
8.80           2481
0.10           2470
7.40           2468
0.29           2467
8.60           2466
3.64           2459
8.40           2454
8.70           2453
3.61           2436
3.58           2425
8.90           2420
7.60           2418
7.80           2414
8.50           2395
3.59           2388
3.63           2380
3.65           2378
9.30           2373
3.71           2362
8.00           2360
0.28           2338
3.66           2336
3.69           2334
9.10           2333
3.68           2333
3.62           2329
8.10           2322
3.76           2317
3.72           2316
9.00           2314
3.67           2299
3.73           2292
9.20           2292
3.75           2248
3.81           2237
9.60           2231
3.74           2231
9.40           2230
9.50           2203
9.70           2194
3.79           2193
3.82           2177
3.78           2173
9.90           2169
3.89           2161
3.84           2150
3.77           2146
3.83           2144
0.27           2135
3.85           2118
9.80           2089
3.92           2089
10.00          2085
3.96           2066
3.86           2064
3.87           2064
3.93           2058
3.88           2051
3.91           2051
3.95           2032
10.20          2023
3.94           2012
3.98           2010
0.26           1998
4.02           1997
4.03           1975
4.07           1974
4.04           1965
0.03           1951
10.10          1949
4.01           1943
3.97           1936
4.05           1907
4.14           1897
4.15           1895
4.06           1886
3.99           1886
10.30          1885
4.13           1873
4.12           1857
4.09           1856
4.11           1838
4.19           1831
10.40          1828
10.60          1813
4.08           1812
10.50          1811
4.27           1802
4.16           1797
10.70          1783
4.22           1782
0.25           1780
4.23           1780
4.17           1774
4.24           1767
4.18           1761
4.33           1761
4.21           1752
4.26           1752
4.36           1747
4.25           1733
4.34           1730
4.29           1721
10.80          1713
0.04           1681
4.32           1681
4.37           1678
4.28           1668
4.45           1665
4.46           1659
4.35           1651
4.44           1643
4.39           1633
4.31           1628
4.38           1622
0.24           1621
4.42           1620
4.43           1615
4.41           1609
10.90          1599
4.55           1591
4.65           1586
4.57           1582
4.58           1578
4.54           1572
4.47           1569
11.00          1557
4.49           1554
4.51           1546
4.48           1544
4.71           1542
4.56           1538
4.61           1536
4.63           1528
4.59           1516
11.10          1506
4.67           1504
4.68           1503
11.40          1499
4.62           1496
4.66           1495
4.72           1476
4.76           1473
4.53           1472
4.52           1470
4.79           1469
4.69           1463
11.30          1463
4.64           1462
4.75           1461
0.23           1459
0.05           1456
4.74           1445
11.20          1441
4.73           1432
4.81           1428
4.82           1422
4.88           1422
4.89           1407
4.77           1392
0.22           1389
11.50          1382
4.84           1380
4.85           1376
4.83           1374
4.95           1370
4.78           1367
5.01           1365
11.70          1365
4.91           1365
4.87           1359
4.86           1356
5.08           1350
4.94           1341
11.60          1339
4.97           1332
4.93           1331
5.04           1324
4.96           1317
4.99           1317
4.92           1316
5.11           1311
4.98           1308
11.80          1301
5.07           1299
5.09           1295
5.17           1292
5.18           1279
5.14           1276
5.02           1276
5.06           1274
5.13           1271
5.21           1269
0.21           1264
5.24           1251
5.12           1238
5.05           1236
5.03           1235
0.06           1232
11.90          1231
5.19           1221
5.27           1218
5.16           1217
5.22           1211
5.23           1201
5.15           1199
5.31           1196
5.41           1189
5.32           1186
5.29           1175
5.35           1172
5.25           1172
5.28           1170
5.26           1159
5.34           1158
12.00          1156
5.39           1153
5.36           1152
5.52           1148
5.45           1144
5.38           1140
5.33           1137
5.44           1135
5.42           1131
5.48           1129
12.10          1126
5.37           1111
5.43           1105
5.49           1104
5.58           1093
17.20          1092
5.47           1086
5.57           1079
12.20          1078
5.54           1075
17.10          1075
0.19           1070
17.50          1069
5.53           1065
5.55           1063
12.40          1058
12.50          1049
17.00          1047
5.59           1046
5.83           1046
5.67           1044
5.46           1041
16.90          1034
5.63           1031
5.56           1028
5.84           1026
17.40          1025
12.30          1023
5.51           1022
5.64           1022
17.30          1020
5.61           1017
16.80          1015
5.65           1014
5.77           1012
0.18           1007
5.62           1004
5.82           1003
5.68           1003
17.70          1002
12.60           999
0.07            998
5.78            997
17.60           995
5.75            993
16.70           990
5.85            988
0.17            987
5.73            981
5.88            976
5.79            971
5.92            971
5.66            968
5.87            967
5.81            962
5.71            961
5.76            959
5.74            953
5.72            950
5.98            949
5.69            948
16.60           946
12.80           946
12.70           941
17.80           940
5.86            938
0.08            938
5.96            937
5.89            935
5.91            931
6.04            929
16.50           926
6.08            923
16.40           922
6.21            919
17.90           917
6.01            917
6.22            916
6.14            915
5.99            911
12.90           910
6.18            907
5.93            907
6.02            906
6.06            905
5.95            904
6.13            904
6.05            898
6.09            894
6.15            894
6.16            891
13.00           888
6.03            886
0.16            884
5.94            883
6.24            883
6.07            878
6.12            878
18.00           877
6.23            869
6.26            866
16.30           866
6.25            862
6.35            860
16.20           858
6.11            855
6.31            852
6.34            851
13.10           851
5.97            847
6.33            843
6.56            841
18.10           839
6.47            838
6.39            837
6.28            836
6.29            835
6.57            835
6.17            834
6.49            832
6.38            831
6.45            830
6.19            829
13.20           828
6.36            827
6.48            823
0.09            823
6.32            822
6.46            821
6.54            821
6.44            820
6.37            819
6.76            818
13.30           816
6.52            815
6.51            815
6.59            815
6.73            810
15.90           808
13.80           805
13.50           804
6.27            803
6.42            802
0.14            799
6.63            798
6.43            798
6.67            790
6.68            789
6.65            789
13.40           787
6.53            787
6.41            786
18.30           783
6.61            782
6.69            779
6.83            778
16.00           777
6.74            776
6.58            774
6.64            774
13.60           774
16.10           771
6.77            770
6.82            766
6.55            766
6.66            766
6.79            764
14.60           760
0.15            759
6.87            759
14.00           758
6.97            757
6.72            753
6.92            752
6.81            750
18.40           747
6.88            746
6.71            745
13.70           744
13.90           742
15.60           742
6.89            742
15.80           741
7.06            740
18.20           740
15.30           739
6.95            736
6.85            733
0.12            730
6.62            730
7.01            730
14.50           730
14.30           730
15.70           729
0.13            727
7.04            725
0.11            723
6.99            723
7.02            721
14.10           720
15.50           719
14.20           715
6.93            715
14.40           713
6.84            711
7.03            711
6.75            709
6.78            708
7.16            708
6.94            706
14.90           702
7.24            701
15.40           701
7.13            698
15.00           697
6.91            695
6.86            691
7.31            690
7.11            689
7.07            688
7.18            687
6.98            686
7.21            685
14.70           684
6.96            682
7.09            678
15.20           673
7.08            672
18.60           670
15.10           670
7.49            669
7.12            667
14.80           666
7.35            663
7.23            659
7.25            657
8.44            657
7.33            656
8.48            656
7.79            656
7.17            655
7.37            655
7.99            654
7.32            654
7.38            653
7.29            651
7.41            651
7.45            647
7.53            647
7.43            646
7.15            646
7.22            646
7.26            646
7.67            644
7.68            642
18.50           641
7.05            640
7.55            640
7.14            638
7.51            635
7.36            635
8.34            633
7.42            630
8.65            630
7.54            630
8.51            630
8.46            630
8.31            629
8.57            627
8.24            627
8.02            626
8.62            626
7.19            625
8.32            625
8.23            624
8.39            624
8.73            624
7.52            624
7.58            623
7.39            622
8.18            622
8.42            622
8.81            622
8.37            621
8.14            621
7.61            621
7.75            620
7.91            619
7.66            618
8.63            618
7.34            618
8.43            618
8.01            617
7.27            616
9.28            616
8.69            616
8.88            615
8.04            615
7.69            614
8.17            614
7.89            613
8.08            612
7.97            611
7.46            611
7.77            611
8.41            611
18.70           610
7.44            610
8.11            609
8.19            609
7.59            607
8.49            607
7.95            607
8.27            606
8.16            606
7.56            606
8.53            605
8.93            604
7.76            603
8.86            603
9.16            603
8.26            603
7.78            602
18.80           602
8.56            602
7.82            601
8.78            601
8.92            600
8.25            600
8.79            600
7.28            599
7.64            599
8.05            599
7.98            599
9.07            599
8.76            598
8.33            598
8.52            597
9.17            596
8.77            596
8.84            595
7.47            595
8.83            594
7.73            593
7.87            593
8.82            593
8.35            592
8.66            592
8.21            592
8.07            592
9.14            591
7.81            590
8.45            589
8.54            589
8.64            589
8.61            589
8.89            588
8.13            587
8.36            587
8.58            587
8.47            586
8.67            586
18.90           586
7.94            586
7.71            585
8.68            584
8.95            584
8.22            583
7.63            583
7.48            583
8.59            583
8.06            582
9.26            581
8.09            580
9.04            580
9.29            580
7.84            579
8.03            579
9.19            578
7.92            578
9.03            577
8.87            577
9.21            576
8.72            575
8.29            575
9.31            574
7.83            574
8.28            573
9.02            572
7.57            572
7.62            572
8.71            571
8.15            568
9.09            567
9.33            567
8.96            567
7.86            565
8.98            565
7.93            565

In [11]:
# --- Pickup and Dropoff Location id Columns ---
print(df['pickup_location_id'].value_counts())
print(df['dropoff_location_id'].value_counts())

pickup_location_id
237    198008
236    175969
161    161315
132    149312
142    124523
162    120488
186    113921
230    111934
239    108689
79     107374
138    106388
170    102755
234    101697
163    100524
68      99835
141     91725
249     89571
48      89093
238     80807
140     78479
263     77369
164     76704
107     74684
246     74631
229     64770
90      60980
262     59916
114     59066
148     56529
231     56346
113     55962
43      54474
100     49800
143     48875
137     47174
144     44972
158     42773
233     42050
151     35020
75      34338
211     33427
166     30217
87      29127
50      28135
13      24652
41      21083
125     19814
74      18016
4       17736
261     17472
42      15194
88      15040
232     14286
24      13801
244     10841
224     10796
255     10447
45      10285
116      9673
145      9042
209      8894
70       8621
7        7776
61       7527
226      7010
256      6932
37       6675
112      6587
152      6565
97       6216
33       5816
80       5603
66       5538
65       5417
76       5381
243      4936
225      4896
25       4854
264      4734
181      4332
188      4187
17       4101
49       4067
146      3878
89       3865
129      3847
36       3783
39       3625
130      3201
35       3179
216      3005
179      2927
193      2872
223      2799
72       2749
177      2679
168      2651
91       2516
71       2425
82       2115
95       2090
260      2068
228      2052
127      2045
62       2033
189      1897
10       1883
55       1883
247      1865
198      1841
157      1814
197      1785
69       1785
14       1771
265      1752
213      1624
51       1563
40       1525
85       1511
159      1510
52       1506
77       1454
195      1443
215      1381
205      1378
92       1332
222      1316
254      1286
235      1282
182      1277
63       1261
167      1258
155      1224
106      1158
86       1123
117      1095
165      1094
12       1078
191      1072
207      1068
210      1062
93       1062
78       1056
26       1056
169      1051
119      1036
218      1033
196       985
18        982
56        969
28        956
220       931
219       919
47        907
241       903
258       882
242       880
123       860
133       856
134       834
174       830
22        791
217       786
34        783
83        769
126       760
248       748
81        741
259       740
227       727
121       726
212       723
250       721
136       690
208       680
29        673
21        650
124       644
185       628
131       628
202       624
60        623
32        613
108       611
257       607
149       597
160       594
200       588
147       586
102       573
20        540
173       527
135       523
139       512
203       505
1         504
180       463
19        412
122       411
38        405
54        402
190       396
150       395
94        392
3         392
67        390
201       324
16        313
11        310
171       294
53        292
183       279
178       278
101       270
98        265
192       252
194       246
252       236
153       231
128       196
64        177
175       168
9         164
240       153
15        149
73        148
46        121
120       101
31         96
6          83
154        72
58         70
96         68
57         57
59         55
184        50
221        45
8          41
214        41
23         36
27         23
115        22
206        22
30         21
172        21
253        19
111        15
251        13
2          12
118        12
156         8
84          6
109         6
187         6
44          5
105         4
245         3
199         3
176         3
Name: count, dtype: int64
dropoff_location_id
236    179446
237    177568
161    138367
142    110032
170    109177
230    109064
239    107804
162    104656
141    100319
68      97921
234     91489
163     91274
79      90723
238     88091
48      87034
246     82612
263     82001
140     79371
229     78312
186     76263
164     75980
107     73262
249     71060
231     67070
262     61236
143     59031
90      55869
233     55191
137     53312
148     50626
113     49225
75      48703
100     43952
158     42852
114     41904
50      40797
43      39728
144     39555
138     39127
87      37879
132     36900
211     35747
151     35604
166     35252
74      31617
13      29359
41      28111
232     24295
42      22750
4       21354
125     20937
244     20864
88      19853
261     19009
265     17331
224     17083
24      14741
116     14630
45      13784
145     13155
255     12717
112     12670
243     12215
209     11989
181     11970
7       11771
33      11626
256     11431
61      10941
37       9301
152      8083
25       8063
226      7860
97       7845
1        7726
65       7580
49       7431
225      7333
80       7318
17       7059
66       6858
76       6586
188      6070
89       6024
95       5914
223      5850
127      5664
129      5613
36       5419
216      5086
179      4649
93       4607
130      4437
264      4395
189      4359
39       4298
198      4156
168      4042
146      3964
10       3949
82       3932
14       3883
228      3705
193      3658
40       3626
35       3281
92       3276
260      3120
62       3073
177      2923
72       2899
52       2874
91       2853
71       2608
69       2606
247      2540
157      2439
197      2416
195      2372
56       2348
28       2331
220      2321
205      2219
55       2200
106      2147
202      2142
196      2101
159      2077
26       1983
257      1978
155      1955
85       1905
213      1897
70       1889
215      1882
219      1854
200      1844
165      1834
51       1824
134      1759
63       1743
77       1713
235      1711
218      1678
217      1669
254      1640
191      1636
12       1610
119      1571
174      1554
86       1546
18       1539
210      1519
133      1509
258      1508
169      1492
160      1481
222      1480
241      1479
167      1439
242      1438
182      1423
227      1421
78       1415
124      1398
123      1371
135      1365
121      1364
83       1324
22       1304
20       1250
185      1230
117      1207
208      1192
102      1180
131      1146
47       1127
139      1127
126      1105
203      1100
173      1098
21       1077
136      1053
149      1038
250      1037
54       1037
194      1025
29        998
67        985
38        957
259       954
207       946
16        940
171       899
252       882
32        875
212       871
248       858
81        858
34        853
147       847
180       806
190       787
19        762
53        741
98        696
3         691
60        690
108       687
94        660
201       639
128       604
150       593
64        577
11        559
122       552
101       550
175       542
192       541
15        516
178       514
183       487
154       471
9         451
73        443
31        378
153       349
240       301
120       286
46        195
96        182
58        134
206       125
6         124
57        118
184       111
23        101
214        93
221        86
8          80
253        79
172        73
118        70
27         67
59         66
245        57
111        52
30         49
115        49
251        45
176        32
84         32
109        32
156        26
187        24
204        21
44         19
2          16
5           8
99          3
Name: count, dtype: int64

In [12]:
# --- Payment Type Column ---
print(df['payment_type'].value_counts())
print(df['payment_type'].value_counts().sum())

payment_type
Credit card       2727585
Flex Fare trip     955371
Cash               372909
Dispute             22987
No charge           11984
Name: count, dtype: int64
4090836

In [13]:
print(df[['fare_amount', 'tip_amount', 'total_amount']].describe())

       fare_amount  tip_amount  total_amount
count   4090836.00  4090836.00    4090836.00
mean         21.51        2.98         30.49
std          19.01        4.02         22.97
min        -950.00      -47.10       -951.00
25%          10.00        0.00         17.64
50%          16.30        2.24         23.94
75%          26.80        4.10         34.95
max        5525.99      239.00       5530.74

### Empty Passenger Counts

In [14]:
empty_passenger_count = df[df['passenger_count'].isna()]
empty_passenger_count.shape[0]

955371

In [15]:
empty_passenger_count["payment_type"].value_counts()

payment_type
Flex Fare trip    955371
Name: count, dtype: int64

In [16]:
empty_passenger_count[["fare_amount", "tip_amount", "total_amount"]].describe()

       fare_amount  tip_amount  total_amount
count    955371.00   955371.00     955371.00
mean         25.83        0.48         32.74
std          14.33        1.91         16.99
min         -18.30        0.00        -23.05
25%          16.19        0.00         21.74
50%          23.20        0.00         29.11
75%          32.21        0.00         39.56
max        1061.72       67.20       1065.72

### Zero Passenger Count

In [17]:
zero_passenger_count = df[df['passenger_count']==0]
zero_passenger_count.shape[0]

12533

In [18]:
zero_passenger_count["trip_distance"].value_counts()

trip_distance
0.90      562
1.00      514
0.70      514
0.80      477
1.10      475
0.00      449
1.20      446
0.60      438
1.30      419
1.40      388
0.50      378
1.50      375
1.60      356
1.70      343
1.80      329
0.40      280
1.90      269
2.00      258
2.10      247
2.20      196
2.30      195
2.40      181
0.30      162
2.60      159
2.50      152
2.70      140
2.80      132
3.10      122
3.20      101
3.00      101
2.90       97
3.30       90
3.40       87
0.20       76
3.50       71
3.70       69
3.60       56
3.90       56
3.80       45
4.10       44
4.00       44
4.20       43
4.50       41
0.10       40
4.30       34
4.80       33
4.60       32
4.40       32
4.70       31
4.90       28
5.10       26
5.00       25
5.30       24
5.40       24
5.50       22
5.20       21
5.60       21
6.20       20
8.20       20
6.30       19
9.70       19
5.90       19
7.30       18
6.00       18
6.70       18
6.10       18
7.50       16
5.70       16
8.40       15
11.70      15
7.20       15
6.60       15
10.10      15
6.90       15
6.50       14
8.70       14
5.80       14
6.40       14
10.30      14
10.50      13
7.00       13
7.80       13
8.30       13
10.60      13
10.00      13
9.20       12
7.10       12
7.70       12
9.40       12
6.80       12
7.90       11
18.10      11
9.00       11
8.00       11
17.20      11
16.50      11
10.70      11
1.01       10
18.30      10
9.10       10
7.60       10
10.90      10
9.80        9
9.60        9
16.70       9
8.90        9
7.40        9
9.50        9
11.20       9
1.33        9
8.80        9
18.00       9
1.02        9
0.84        9
11.00       9
10.40       9
17.40       8
17.50       8
0.98        8
8.50        8
0.74        8
9.90        8
16.90       8
0.87        8
11.90       8
1.22        8
17.90       8
0.56        8
16.80       8
13.00       8
18.40       8
1.21        8
10.80       7
0.51        7
1.77        7
1.48        7
0.94        7
17.10       7
0.72        7
1.49        7
0.79        7
17.00       7
1.12        7
1.26        7
2.25        7
10.20       7
0.95        7
11.60       7
1.66        7
1.47        7
17.70       6
17.60       6
1.63        6
20.00       6
0.69        6
11.10       6
1.56        6
0.93        6
2.28        6
17.30       6
1.15        6
9.30        6
1.34        6
0.67        6
1.98        6
8.60        6
0.91        6
1.45        6
8.10        6
1.76        6
0.65        6
1.57        6
1.17        6
11.30       6
1.18        6
2.04        6
0.49        6
11.50       5
1.55        5
1.59        5
1.04        5
0.55        5
0.88        5
0.01        5
1.74        5
19.50       5
1.52        5
0.68        5
1.14        5
12.20       5
1.36        5
1.24        5
0.78        5
11.80       5
1.92        5
0.58        5
0.53        5
1.54        5
1.93        5
1.43        5
1.32        5
0.97        5
1.27        5
0.83        5
1.53        5
1.42        5
0.96        5
1.11        5
1.51        5
1.71        5
3.17        4
0.99        4
2.31        4
12.80       4
0.46        4
0.85        4
1.13        4
2.48        4
1.84        4
0.54        4
21.90       4
12.50       4
20.30       4
16.10       4
1.44        4
0.47        4
11.40       4
18.70       4
0.92        4
2.18        4
3.29        4
1.61        4
1.69        4
1.29        4
19.60       4
0.76        4
2.52        4
1.94        4
2.45        4
1.68        4
1.58        4
1.83        4
1.06        4
0.73        4
16.30       4
1.05        4
19.40       4
2.17        4
12.10       4
1.81        4
1.65        4
0.71        4
1.16        4
19.80       4
1.23        4
1.35        4
14.60       3
1.08        3
2.75        3
20.10       3
2.15        3
2.73        3
2.47        3
2.55        3
0.77        3
1.87        3
20.20       3
5.46        3
4.08        3
1.82        3
4.54        3
12.70       3
1.41        3
0.39        3
12.30       3
18.20       3
15.00       3
14.30       3
16.40       3
18.90       3
13.10       3
1.46        3
12.00       3
1.99        3
0.57        3
4.73        3
0.82        3
2.61        3
0.75        3
20.40       3
1.38        3
3.33        3
18.80       3
1.89        3
2.34        3
2.29        3
0.81        3
0.48        3
20.70       3
1.85        3
17.80       3
2.13        3
15.90       3
1.67        3
1.88        3
2.33        3
2.21        3
0.34        3
3.28        3
2.03        3
1.75        3
3.18        3
1.64        3
1.31        3
0.61        3
2.09        3
1.28        3
2.06        3
15.20       3
1.03        3
2.26        3
2.02        3
1.19        3
0.29        3
2.76        3
3.04        2
1.09        2
3.26        2
21.10       2
21.30       2
19.00       2
3.31        2
1.86        2
3.94        2
3.11        2
4.42        2
2.05        2
14.50       2
2.82        2
3.32        2
3.48        2
2.49        2
13.70       2
2.39        2
2.85        2
2.24        2
19.20       2
16.60       2
12.60       2
2.38        2
21.70       2
2.63        2
3.19        2
2.54        2
14.00       2
2.16        2
1.62        2
15.50       2
5.78        2
19.90       2
3.72        2
0.45        2
0.44        2
21.60       2
2.83        2
2.51        2
0.66        2
4.09        2
3.16        2
4.16        2
1.78        2
0.37        2
4.57        2
2.11        2
20.60       2
14.10       2
1.79        2
0.62        2
14.80       2
2.97        2
13.20       2
3.14        2
1.39        2
2.86        2
3.77        2
5.38        2
2.08        2
2.27        2
2.84        2
14.20       2
3.03        2
2.87        2
19.10       2
1.25        2
2.32        2
3.37        2
0.52        2
0.63        2
0.26        2
2.67        2
19.70       2
2.98        2
3.88        2
3.75        2
3.73        2
2.57        2
3.13        2
5.97        2
0.86        2
21.80       2
15.30       2
1.96        2
0.64        2
0.89        2
2.92        2
4.47        2
2.88        2
2.53        2
3.08        2
0.59        2
2.89        2
2.43        2
1.95        2
1.73        2
0.31        2
3.91        2
12.90       2
2.22        2
4.94        2
2.44        2
13.40       2
5.93        2
4.23        2
3.02        2
22.10       1
3.76        1
2.72        1
4.83        1
6.45        1
2.56        1
6.13        1
3.97        1
1.37        1
3.21        1
14.08       1
2.36        1
4.93        1
16.69       1
4.82        1
24.60       1
14.90       1
20.50       1
18.50       1
13.38       1
24.50       1
30.00       1
15.60       1
5.28        1
12.40       1
22.20       1
3.56        1
0.02        1
20.90       1
7.62        1
22.70       1
3.25        1
3.09        1
17.79       1
26.80       1
17.01       1
1.72        1
16.66       1
4.96        1
21.50       1
22.40       1
18.60       1
13.30       1
3.57        1
28.20       1
13.60       1
57.80       1
16.00       1
5.36        1
5.02        1
3.58        1
4.79        1
2.14        1
7.02        1
101.50      1
23.90       1
16.65       1
3.15        1
3.45        1
6.36        1
3.62        1
3.35        1
6.25        1
2.65        1
30.40       1
0.38        1
5.52        1
3.89        1
1.97        1
25.40       1
8.58        1
3.68        1
6.33        1
4.28        1
6.63        1
9.12        1
6.04        1
4.48        1
2.01        1
3.07        1
29.10       1
9.18        1
2.59        1
6.24        1
20.97       1
23.00       1
23.60       1
5.33        1
4.43        1
4.05        1
10.62       1
8.68        1
11.62       1
4.19        1
4.75        1
21.40       1
36.20       1
8.41        1
4.61        1
2.19        1
4.38        1
8.21        1
0.27        1
4.36        1
4.72        1
4.21        1
15.07       1
5.65        1
6.01        1
7.19        1
8.11        1
3.65        1
3.38        1
4.14        1
5.31        1
3.59        1
7.07        1
2.81        1
6.44        1
3.27        1
32.20       1
3.96        1
3.24        1
4.22        1
2.23        1
3.23        1
29.20       1
3.67        1
34.50       1
15.10       1
1.91        1
20.80       1
5.06        1
3.63        1
10.37       1
2.99        1
9.58        1
10.53       1
3.01        1
4.58        1
7.89        1
6.07        1
4.13        1
2.12        1
8.66        1
0.28        1
3.36        1
0.12        1
0.42        1
2.78        1
3.53        1
5.59        1
6.58        1
2.71        1
23.40       1
6.99        1
3.22        1
8.98        1
3.39        1
10.36       1
15.09       1
4.12        1
2.62        1
0.41        1
3.64        1
5.03        1
2.07        1
21.00       1
3.52        1
4.25        1
4.99        1
2.77        1
3.85        1
2.95        1
27.40       1
23.30       1
9.64        1
22.60       1
24.80       1
15.40       1
6.09        1
4.78        1
2.64        1
2.35        1
8.88        1
3.54        1
0.23        1
0.43        1
0.07        1
2.46        1
2.74        1
5.63        1
2.91        1
11.25       1
22.80       1
6.97        1
11.84       1
0.32        1
3.78        1
47.40       1
2.66        1
8.76        1
7.33        1
9.08        1
8.75        1
22.90       1
14.70       1
3.05        1
21.20       1
7.65        1
4.69        1
5.74        1
4.95        1
4.11        1
4.62        1
2.69        1
6.34        1
0.21        1
4.32        1
20.28       1
16.97       1
Name: count, dtype: int64

In [19]:
zero_passenger_count[['fare_amount', 'tip_amount', 'total_amount']].describe()

       fare_amount  tip_amount  total_amount
count     12533.00    12533.00      12533.00
mean         17.39        3.31         26.30
std          20.53        3.75         23.65
min         -32.10       -0.90        -34.35
25%           8.60        1.00         15.55
50%          12.80        2.80         20.55
75%          19.80        4.29         28.85
max        1400.00      150.00       1400.00

### Zero trip distance

In [20]:
zero_trip_distance = df[df['trip_distance']==0]
zero_trip_distance.shape[0]

113031

In [21]:
zero_trip_distance["passenger_count"].value_counts()

passenger_count
1.00    28491
2.00     4539
4.00     2412
3.00     1104
0.00      449
5.00       46
6.00       21
8.00        2
9.00        1
Name: count, dtype: int64

In [22]:
zero_trip_distance[['fare_amount', 'tip_amount', 'total_amount']].describe()

       fare_amount  tip_amount  total_amount
count    113031.00   113031.00     113031.00
mean         29.75        1.61         36.40
std          36.40        4.95         38.69
min        -950.00      -14.95       -951.00
25%          14.00        0.00         19.23
50%          23.55        0.00         29.25
75%          37.12        0.00         43.93
max        5525.99      239.00       5530.74

### Negative Fares

In [23]:
negative_fares = df[(df['fare_amount'] < 0) | (df['tip_amount'] < 0) | (df['total_amount'] < 0)]
negative_fares.shape[0]

14888

In [24]:
negative_fares["payment_type"].value_counts()

payment_type
Dispute           9044
Cash              3850
No charge         1620
Credit card        361
Flex Fare trip      13
Name: count, dtype: int64

In [25]:
negative_fares[["trip_distance","fare_amount","tip_amount","total_amount"]].describe()

       trip_distance  fare_amount  tip_amount  total_amount
count       14888.00     14888.00    14888.00      14888.00
mean            3.33       -22.15       -0.02        -28.07
std             5.73        32.56        0.72         34.18
min             0.00      -950.00      -47.10       -951.00
25%             0.25       -25.40        0.00        -31.25
50%             1.13       -11.40        0.00        -17.15
75%             3.18        -5.10        0.00        -10.50
max            93.18         0.00        4.51         40.76

### Pickup & Dropoff Datetime

In [26]:
df[df['pickup_datetime'] < datetime(2026,5,1)]

,pickup_datetime,dropoff_datetime,passenger_count,trip_distance,pickup_location_id,dropoff_location_id,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
40,2026-04-30 23:53:41,2026-05-01 00:14:20,2.00,8.76,138,161,Credit card,35.90,6.00,0.50,11.22,7.46,1.00,67.33,2.50,2.00,0.75
84,2026-04-30 23:54:52,2026-05-01 00:11:11,5.00,2.93,239,166,Credit card,18.40,1.00,0.50,4.68,0.00,1.00,28.08,2.50,0.00,0.00
163,2026-04-30 23:59:17,2026-05-01 00:12:36,1.00,2.42,144,170,Credit card,14.90,1.00,0.50,4.13,0.00,1.00,24.78,2.50,0.00,0.75
390,2026-04-30 23:59:17,2026-05-01 00:27:55,1.00,5.69,209,236,Cash,29.60,1.00,0.50,0.00,0.00,1.00,35.35,2.50,0.00,0.75
585,2026-04-30 23:51:13,2026-05-01 00:28:20,5.00,9.58,88,41,Credit card,47.80,1.00,0.50,0.00,0.00,1.00,53.55,2.50,0.00,0.75
946,2026-04-30 23:51:53,2026-04-30 23:58:30,1.00,1.06,170,137,Credit card,8.60,1.00,0.50,0.05,0.00,1.00,14.40,2.50,0.00,0.75
958,2026-04-30 23:47:18,2026-04-30 23:53:05,5.00,1.24,50,246,Credit card,7.90,1.00,0.50,4.10,0.00,1.00,17.75,2.50,0.00,0.75
1310,2026-04-30 23:49:52,2026-05-01 00:04:47,1.00,1.53,68,234,Cash,13.50,1.00,0.50,0.00,0.00,1.00,19.25,2.50,0.00,0.75
1402,2026-04-30 23:54:59,2026-05-01 00:12:16,1.00,2.27,114,87,Cash,13.50,1.00,0.50,0.00,0.00,1.00,19.25,2.50,0.00,0.75
2125,2026-04-30 23:54:59,2026-05-01 00:36:14,1.00,16.61,138,14,Cash,68.10,6.00,0.50,0.00,0.00,1.00,77.60,0.00,2.00,0.00
2314,2026-04-30 23:50:39,2026-04-30 23:57:37,1.00,1.04,263,236,Credit card,8.60,1.00,0.50,2.72,0.00,1.00,16.32,2.50,0.00,0.00
902678,2008-12-31 23:05:53,2009-01-01 18:07:17,1.00,2.28,264,264,Credit card,17.70,0.00,0.50,4.49,0.00,1.00,26.94,2.50,0.00,0.75
2186371,2009-01-01 15:33:07,2009-01-01 17:08:07,1.00,13.01,138,90,Credit card,79.30,0.00,0.50,12.00,14.92,1.00,110.97,2.50,0.00,0.75

### Clean Suspicious Data

In [27]:
print(f"Current DataFrame shape: {df.shape}")
cleaned_df = df[ (df["fare_amount"] >= 0) & (df["tip_amount"] >= 0) & (df["total_amount"] >= 0)].copy()
print(f"DataFrame shape after dropping negative fares: {cleaned_df.shape}")
cleaned_df = cleaned_df[cleaned_df["passenger_count"].isna() | (cleaned_df["passenger_count"] > 0)]
print(f"DataFrame shape after dropping 0 passengers: {cleaned_df.shape}")
cleaned_df = cleaned_df[cleaned_df["trip_distance"]>0]
print(f"DataFrame shape after dropping 0 trip distances: {cleaned_df.shape}")
cleaned_df = cleaned_df[cleaned_df['pickup_datetime'] >= datetime(2026,5,1)]
print(f"DataFrame shape after dropping pickup dates older than 2026-05-01: {cleaned_df.shape}")

Current DataFrame shape: (4090836, 17)
DataFrame shape after dropping negative fares: (4075948, 17)
DataFrame shape after dropping 0 passengers: (4063425, 17)
DataFrame shape after dropping 0 trip distances: (3952609, 17)
DataFrame shape after dropping pickup dates older than 2026-05-01: (3952596, 17)

In [28]:
cleaned_df.isna().sum()

pickup_datetime               0
dropoff_datetime              0
passenger_count          879392
trip_distance                 0
pickup_location_id            0
dropoff_location_id           0
payment_type                  0
fare_amount                   0
extra                         0
mta_tax                       0
tip_amount                    0
tolls_amount                  0
improvement_surcharge         0
total_amount                  0
congestion_surcharge     879392
Airport_fee              879392
cbd_congestion_fee            0
dtype: int64

In [29]:
cleaned_df["passenger_count"].value_counts()

passenger_count
1.00    2540002
2.00     388529
3.00      82398
4.00      50155
5.00       7599
6.00       4520
8.00          1
Name: count, dtype: int64

In [30]:
cleaned_df["payment_type"].value_counts()

payment_type
Credit card       2695650
Flex Fare trip     879392
Cash               358216
Dispute             11931
No charge            7407
Name: count, dtype: int64

In [31]:
cleaned_df[["pickup_datetime","dropoff_datetime","trip_distance","pickup_location_id","dropoff_location_id","fare_amount","tip_amount","total_amount"]].describe()

,pickup_datetime,dropoff_datetime,trip_distance,pickup_location_id,dropoff_location_id,fare_amount,tip_amount,total_amount
count,3952596,3952596,3952596.00,3952596.00,3952596.00,3952596.00,3952596.00,3952596.00
mean,2026-05-16 10:21:31.977615,2026-05-16 10:40:25.085140,5.11,162.23,161.95,21.44,3.02,30.53
min,2026-05-01 00:00:00,2026-05-01 00:03:33,0.01,1.00,1.00,0.00,0.00,0.00
25%,2026-05-08 21:14:23,2026-05-08 21:31:39,1.10,114.00,112.00,10.00,0.00,17.65
50%,2026-05-16 01:46:50,2026-05-16 02:02:21.500000,1.93,161.00,162.00,16.20,2.33,23.86
75%,2026-05-23 15:46:11,2026-05-23 16:04:07,3.93,234.00,234.00,26.32,4.15,34.81
max,2026-06-01 00:20:35,2026-06-02 12:53:42,307491.47,265.00,265.00,5525.99,222.00,5530.74
std,NaN,NaN,492.00,66.88,70.70,18.01,3.98,22.05

### Mismatch Totals

In [94]:
def calculate_total_amount(row):
    if row["payment_type"] in ["Dispute", "No charge"]:
        return row["fare_amount"] + row["tip_amount"] + row["extra"] + row["mta_tax"] + row["tolls_amount"] + row["improvement_surcharge"] + row["congestion_surcharge"] + row["Airport_fee"] + row["cbd_congestion_fee"]
    elif row["payment_type"] in ["Cash"]:
            return row["fare_amount"] + row["extra"] + row["mta_tax"] + row["tolls_amount"] + row["improvement_surcharge"]
    
    return row["fare_amount"] + row["tip_amount"] + row["extra"] + row["mta_tax"] + row["tolls_amount"] + row["improvement_surcharge"]

cleaned_df["calc_total_amount"] = cleaned_df.apply(calculate_total_amount, axis=1)

cleaned_df["total_amount_check"] = cleaned_df["calc_total_amount"] == cleaned_df["total_amount"]

cleaned_df["total_amount_check"].value_counts()

total_amount_check
False    3195344
True      757252
Name: count, dtype: int64

In [62]:
cleaned_df["difference"] = (
    cleaned_df["total_amount"] - cleaned_df["calc_total_amount"]
)
cleaned_df["difference"] = cleaned_df["difference"].round(2)
cleaned_df["difference"].describe()

count   3952596.00
mean          2.90
std           3.60
min         -55.74
25%           2.50
50%           3.25
75%           3.25
max         323.89
Name: difference, dtype: float64

In [74]:
filtered_df = cleaned_df[(cleaned_df['difference'] != 0.00) & (cleaned_df['difference'].notna())][["passenger_count","trip_distance", "payment_type","fare_amount", "tip_amount", "extra", "mta_tax", "tolls_amount", "improvement_surcharge", "congestion_surcharge", "Airport_fee", "cbd_congestion_fee", "total_amount", "calc_total_amount", "difference"]]
filtered_df.shape

(3143560, 15)

In [75]:
filtered_df["possible_difference_charges_incl_improvement_surcharge"] = filtered_df["improvement_surcharge"] + filtered_df["congestion_surcharge"] + filtered_df["Airport_fee"] + filtered_df["cbd_congestion_fee"]

filtered_df["possible_difference_charges_excl_improvement_surcharge"] = filtered_df["congestion_surcharge"] + filtered_df["Airport_fee"] + filtered_df["cbd_congestion_fee"]

In [76]:
filtered_df["payment_type"].value_counts()

payment_type
Credit card       2061885
Flex Fare trip     789116
Cash               283881
No charge            5478
Dispute              3200
Name: count, dtype: int64

In [84]:
filtered_df[abs(filtered_df['difference'])==filtered_df['possible_difference_charges_incl_improvement_surcharge']].shape[0]

11210

In [85]:
filtered_df[abs(filtered_df['difference'])==filtered_df['possible_difference_charges_excl_improvement_surcharge']].shape[0]

2330120

In [88]:
filtered_df[abs(filtered_df['difference'])==filtered_df['improvement_surcharge']].shape[0]

2638

In [90]:
filtered_df[
    (abs(filtered_df['difference'])!=filtered_df['possible_difference_charges_excl_improvement_surcharge']) & 
    (abs(filtered_df['difference'])!=filtered_df['possible_difference_charges_incl_improvement_surcharge']) & 
    (abs(filtered_df['difference'])!=filtered_df['improvement_surcharge'])
    ].shape[0]

799985

In [92]:
cleaned_df[cleaned_df['payment_type']=='Cash']['tip_amount'].value_counts()

tip_amount
0.00     358191
4.91          2
5.68          1
9.81          1
8.07          1
20.20         1
2.31          1
6.59          1
2.81          1
6.40          1
3.15          1
5.55          1
4.00          1
2.67          1
8.40          1
6.87          1
2.50          1
2.73          1
2.25          1
6.31          1
4.63          1
2.00          1
3.85          1
1.00          1
7.15          1
Name: count, dtype: int64

In [ ]:
cleaned_df = cleaned_df.drop(columns=["calc_total_amount", "total_amount_check", "difference"])
cleaned_df.columns

Index(['pickup_datetime', 'dropoff_datetime', 'passenger_count',
       'trip_distance', 'pickup_location_id', 'dropoff_location_id',
       'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount',
       'tolls_amount', 'improvement_surcharge', 'total_amount',
       'congestion_surcharge', 'Airport_fee', 'cbd_congestion_fee'],
      dtype='str')

In [97]:
cleaned_df.to_parquet("../data/cleaned/NYC_Trips.parquet")

In [4]:
import pandas as pd
temp = pd.read_parquet("../data/cleaned/NYC_Trips.parquet")
temp = temp.rename(columns={"Airport_fee":"airport_fee"})
temp.to_parquet("../data/cleaned/NYC_Trips.parquet")